### PR TITLE
nvidia jetson hw support

### PR DESCRIPTION
**Pull request by IamShubhamGupto**
Hello @tridao 

similar to https://github.com/state-spaces/mamba/pull/262

### CODE REVIEW

**Comment by as501226107** [comment]
Thank you very much for your contribution to MAMBA. May I ask how we can install MAMBASSM on Jetson orin nx? Do you have WHL files?

**Comment by IamShubhamGupto** [comment]
> Thank you very much for your contribution to MAMBA. May I ask how we can install MAMBASSM on Jetson orin nx? Do you have WHL files?

Here's a docker image for Jetpack 5.1 - https://hub.docker.com/r/shubhamgupto/mamba

Running the example Mamba code should work

**Comment by as501226107** [comment]
My experiment needs to be run on Jetson. I tried for a long time but could not install the mamba library! Thank you so much!!!Thank you very much!!!
&nbsp;


沈志龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月6日(星期五) 上午10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Dao-AILab/causal-conv1d] nvidia jetson hw support (PR #20)














  
Thank you very much for your contribution to MAMBA. May I ask how we can install MAMBASSM on Jetson orin nx? Do you have WHL files?
  
Here's a docker image for Jetpack 5.1 - https://hub.docker.com/r/shubhamgupto/mamba
 
Running the example Mamba code should work

**Comment by as501226107** [comment]
I'm very sorry to bother you again. After downloading the Docker you provided, I kept getting the following error when running the model with MAMBA. However, other models can run normally in Docker. Do you know the reason for this? I have been trying for a long time on my own and have been unable to solve it before bothering you again. I am very sorry!


NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].


CPU: registered at /torchvision/torchvision/csrc/ops/cpu/nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at /torchvision/torchvision/csrc/ops/quantized/cpu/qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at /tmp/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /tmp/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at /tmp/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at /tmp/pytorch/aten/src/ATen/FunctionalizeFallbackKernel.cpp:290 [backend fallback]
Named: registered at /tmp/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /tmp/pytorch/aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at /tmp/pytorch/aten/src/ATen/native/NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at /tmp/pytorch/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at /tmp/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at /tmp/pytorch/torch/csrc/autograd/TraceTypeManual.cpp:296 [backend fallback]
AutocastCPU: fallthrough registered at /tmp/pytorch/aten/src/ATen/autocast_mode.cpp:382 [backend fallback]
AutocastCUDA: fallthrough registered at /tmp/pytorch/aten/src/ATen/autocast_mode.cpp:249 [backend fallback]
FuncTorchBatched: registered at /tmp/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:710 [backend fallback]
FuncTorchVmapMode: fallthrough registered at /tmp/pytorch/aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at /tmp/pytorch/aten/src/ATen/LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at /tmp/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at /tmp/pytorch/aten/src/ATen/functorch/TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at /tmp/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at /tmp/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at /tmp/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at /tmp/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:157 [backend fallback]




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dragon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 中午11:03
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [Dao-AILab/causal-conv1d] nvidia jetson hw support (PR #20)



 My experiment needs to be run on Jetson. I tried for a long time but could not install the mamba library! Thank you so much!!!Thank you very much!!!
&nbsp;





------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月6日(星期五) 上午10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Dao-AILab/causal-conv1d] nvidia jetson hw support (PR #20)














  
Thank you very much for your contribution to MAMBA. May I ask how we can install MAMBASSM on Jetson orin nx? Do you have WHL files?
  
Here's a docker image for Jetpack 5.1 - https://hub.docker.com/r/shubhamgupto/mamba
 
Running the example Mamba code should work

**Pull request merged**
